# -*- coding: utf-8 -*-
"""Assignment1_Sharath.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Z3vQ_qi-Ok6jqdP42NvelCqD6ykFWge
"""

import re

def register():
  db = open("data.txt","r")
  d = []
  f = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip()
    d.append(a)
    f.append(b)
  data = dict(zip(d, f))
  xxx = input("Create Username:")
  email = "^[a-zA-Z-_]+@[a-zA-Z0-9]+\.[a-z]{1,3}$"
  if re.match(email,xxx):
    Username = xxx
  else:
    print('invalid')
    register()
  if Username in d:
      print("username exists, Please use different username")
      register()
  Pass = input("Create Password:")
  password = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{6,20}$"
  while not re.match(password,Pass):
    Pass = input("Create Password:")
    
  Password = Pass 
  Password1 = input("Confirm Password:")
  d = []
  f = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip()
    d.append(a)
    f.append(b)
  data = dict(zip(d, f))

  if Password != Password1:
     print("Passwords dont match, restart")
     register()
  else:
    if len(Password)<=5:
      print("Password too short, restart:")
      register()
    elif Username in d:
      print("username exists, Please use different username")
      register()
    else:
      db = open("data.txt","a+")
      if len(db.read(100))>0:
        db.write("\n")
      print("Success!")
      db.write("\n") 
      db.write(Username+", "+Password)

def get_pass(username):
  with open("data.txt","r") as db:  
    for i in db:
      a,b = i.split(", ")
      a = a.strip()
      b = b.strip()
      if a==username:
        return b
  return None

def login():
  db = open("data.txt","r")
  Username = ""
  while Username=="":
    Username = input("Enter Username:").strip()

  Password = input("Enter Password (If Forgotten, Enter Nothing):")
  Password = Password.strip()
  if Password=="":
    passwd = get_pass(Username)
    if passwd==None:
      print("no such user")
    else:
      print(passwd)
    return 

  if not len(Username or Password)<1:
    d = []
    f = []
    for i in db:
      a,b = i.split(", ")
      b = b.strip()
      d.append(a)
      f.append(b)
    data = dict(zip(d, f))

    try:
      if data[Username]:
        try:
          if Password == data[Username]:
            print("Login success")
            print("Hello", Username)
          else:
            print('Password or Username incorrect')
        except:
          print("incorrect password or Username")
      else:
        print("Username doesn't exist")
    except:
      print("Login error")

def home(option=None):
  option = input("Login | Signup:")
  if option == "Login":
    login()
  elif option == "Signup":
    register()
  else:
    print("Please enter a option")

home()

